propeldata/ui-kit

.github/ISSUE_TEMPLATE/feature_request.md
=> feature request template

.github/workflows/publish.yml
Need to
1. Remove the BUILDEVENTS_API_KEY stuff.
2. Remove the CodeArtifact stuff.
3. Grant access to the Slack secrets.
=> chore: fix the pipeline

yarn.lock
=> Revert "Fix/time series begin at zero"

packages/react/time-series/README.md, packages/react/time-series/src/TimeSeries.tsx, packages/react/time-series/src/defaults.ts, packages/react/time-series/src/types.ts
=> Revert "Add `beginAtZero` style for Timeseries line"

README.md, packages/react/counter/README.md, packages/react/leaderboard/README.md, packages/react/time-series/README.md
This PR fixes broken images in readme files around the repo by using the static files instead of the storybook ones.
```md
- Fixed readme images.
- Fixed readme images.
- Fixed readme images.
```
=> Fix images in readme files

PRINCIPLES.md
This PR introduces a minor grammatical improvement in PRINCIPLES.md.
=> A minor grammatical improvement in PRINCIPLES.md

packages/ui-kit/src/components/TimeSeries/utils.test.ts, packages/ui-kit/src/components/TimeSeries/utils.ts, turbo.json, yarn.lock
This PR adds support for month granularity in a range of years for the label based granularity feature
```md
- Added support for month granularity in a range of years.
```
=> Label based granularity support for month in years range

.pnp.cjs, .pnp.loader.mjs, yarn.lock
This PR fixes [the broken prod build](https://vercel.com/propeldata/ui-kit/8aMF1aJt1vM93DWbfoUbLA7B4hSB).
=> fix(deps): update lock files

.pnp.cjs, .pnp.loader.mjs, packages/ui-kit/src/components/Counter/Counter.tsx, packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx, packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx, yarn.lock
This PR fixes `415 (Unsupported Media Type)` error introduced in https://github.com/propeldata/ui-kit/pull/129.
=> fix(components): fix 415 (Unsupported Media Type)

app/examples/react-16/package.json, app/examples/react-17/package.json, app/examples/react-18/package.json
This PR fixes the [null](https://github.com/changesets/changesets/discussions/1165) appearance in the change logs
=> fix(apps): update package.json versions

app/storybook/documentation/ui-kit/hooks/QueryHooks.mdx, app/storybook/documentation/ui-kit/hooks/useCounter.mdx, app/storybook/documentation/ui-kit/hooks/useLeaderboard.mdx, app/storybook/documentation/ui-kit/hooks/useTimeSeries.mdx
This PR re-deploy the query hook
=> fix(query-hook): deployment

app/storybook/documentation/ui-kit/hooks/useCounter.mdx, app/storybook/documentation/ui-kit/hooks/useLeaderboard.mdx, app/storybook/documentation/ui-kit/hooks/useTimeSeries.mdx, app/storybook/documentation/ui-kit/hooks/useTopValues.mdx
This PR tweaks the documentation for the query hooks. We shouldn't say "proposed" or "would". We should be more direct. I also simplified it a bit.
=> docs: tweak documentation for Query Hooks

.changeset/tall-swans-kick.md, packages/ui-kit/src/hooks/index.ts
This PR exports the useTopValues query hook
=> FIX: export useTopValues

.changeset/bright-snakes-itch.md, packages/ui-kit/src/hooks/index.ts
This PR fixes exports of some hooks/
=> fix: exports

.changeset/funny-forks-watch.md, app/storybook/documentation/ui-kit/hooks/QueryHooks.mdx
This PR adds all Query Hook links to the overview page
=> docs: add all query hook links

.changeset/few-sloths-pretend.md, packages/ui-kit/src/components/Autocomplete/Autocomplete.module.scss, packages/ui-kit/src/components/Autocomplete/Autocomplete.tsx, packages/ui-kit/src/components/FilterProvider/FilterProvider.tsx, packages/ui-kit/src/components/SimpleFilter/SimpleFilter.module.scss, packages/ui-kit/src/components/SimpleFilter/SimpleFilter.tsx
This PR fixes some bugs in the SimpleFilter's input
=> SimpleFilter improvements

.changeset/few-sloths-pretend.md, .changeset/twelve-spoons-cheat.md, packages/ui-kit/src/components/PieChart/PieChart.stories.tsx, packages/ui-kit/src/components/PieChart/PieChart.tsx, packages/ui-kit/src/components/PieChart/PieChart.types.ts, packages/ui-kit/src/helpers/chartUtils/chartUtils.ts
This PR fixes the Pie Chart canvas height and adds class to the label list
=> fix: Pie Chart canvas height and add class to the label list

.pnp.cjs, app/storybook/package.json, package.json, yarn.lock
This PR fixes dependabot alerts
=> Fix dependabot alerts

.changeset/famous-seas-tap.md, packages/ui-kit/src/components/Autocomplete/Autocomplete.module.scss, packages/ui-kit/src/components/Autocomplete/Autocomplete.tsx, packages/ui-kit/src/components/Autocomplete/Autocomplete.types.ts, packages/ui-kit/src/hooks/useTopValues/useTopValues.ts
This PR adds improvements to the `Autocomplete` component in order to make it consistent with the `Select` component, it also adds the clearable feature to the `Autocomplete`
=> Autocomplete style improvements

.changeset/rare-garlics-yell.md, packages/ui-kit/src/components/ThemeProvider/ThemeProvider.tsx
=> Wrap ThemeProvider for components

packages/ui-kit/src/components/PieChart/PieChart.stories.tsx
This PR fixes PieChart stories in storybook
=> Fix PieChart storybook

.changeset/witty-pugs-sell.md, packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx, packages/ui-kit/src/components/Leaderboard/Leaderboard.types.ts, packages/ui-kit/src/components/PieChart/PieChart.types.ts
This PR fixes:
- Leaderboard not working with FilterProvider timeRange
- PieChart legendPosition wrong type
- Leaderboard `accentColors` prop
=> Small fixes

.changeset/pink-news-arrive.md, packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx
This PR removes an unnecessary console log on Leaderboard component
=> Remove unnecessary log

.changeset/cool-donkeys-cheat.md, packages/ui-kit/README.md
=> Fix: update header image in readme

.changeset/ninety-foxes-push.md, packages/ui-kit/src/components/Box/Box.tsx, packages/ui-kit/src/components/Box/Box.types.ts, packages/ui-kit/src/components/Box/index.ts, packages/ui-kit/src/components/Flex/Flex.tsx, packages/ui-kit/src/components/Flex/Flex.types.ts, packages/ui-kit/src/components/Flex/index.ts, packages/ui-kit/src/components/Grid/Grid.tsx, packages/ui-kit/src/components/Grid/Grid.types.ts, packages/ui-kit/src/components/Grid/index.ts, packages/ui-kit/src/components/Link/Link.tsx, packages/ui-kit/src/components/Link/Link.types.ts, packages/ui-kit/src/components/Link/index.ts
=> Link component + exports fix

.changeset/silly-cooks-appear.md, packages/ui-kit/src/components/DataGrid/DataGrid.module.scss, packages/ui-kit/src/components/DataGrid/DataGrid.tsx, packages/ui-kit/src/components/DataGrid/Drawer/Drawer.module.scss, packages/ui-kit/src/hooks/useCounter/useCounter.ts
=> Small DataGrid fixes

.changeset/thick-pets-share.md, packages/ui-kit/src/components/DataGrid/DataGrid.stories.tsx, packages/ui-kit/src/components/DataGrid/DataGrid.tsx, tsconfig.json
=> DataGrid escape cells to prevent commas breaking CSV

.changeset/smart-apples-divide.md, app/storybook/tsconfig.json, packages/ui-kit/jest.config.js, packages/ui-kit/rollup.config.js, packages/ui-kit/src/components/Autocomplete/Autocomplete.tsx, packages/ui-kit/src/components/DataGrid/DataGrid.tsx, packages/ui-kit/src/components/FilterProvider/FilterProvider.stories.tsx, packages/ui-kit/src/components/FilterProvider/FilterProvider.tsx, packages/ui-kit/src/components/FilterProvider/FilterProvider.types.ts, packages/ui-kit/src/components/SimpleFilter/SimpleFilter.tsx, packages/ui-kit/src/components/TimeRangePicker/TimeRangePicker.tsx, packages/ui-kit/src/components/TopValues/TopValues.types.ts, packages/ui-kit/src/components/shared.types.ts, packages/ui-kit/src/helpers/patchMetricInputDataPool/index.ts, packages/ui-kit/src/helpers/patchMetricInputDataPool/patchMetricInputDataPool.ts, packages/ui-kit/src/hooks/useCounter/useCounter.test.tsx, packages/ui-kit/src/hooks/useCounter/useCounter.ts, packages/ui-kit/src/hooks/useDataGrid/useDataGrid.ts, packages/ui-kit/src/hooks/useDataPoolColumns/useDataPoolColumns.ts, packages/ui-kit/src/hooks/useLeaderboard/useLeaderboard.ts, packages/ui-kit/src/hooks/useRecordsById/useRecordsById.ts, packages/ui-kit/src/hooks/useTimeSeries/useTimeSeries.ts, packages/ui-kit/src/hooks/useTopValues/useTopValues.ts, packages/ui-kit/tsconfig.build.json, packages/ui-kit/tsconfig.json
=> FilterProvider: Add `defaultTimeRange` and `defaultDataPool`

.changeset/thick-dolls-kick.md, packages/ui-kit/src/components/FilterProvider/FilterProvider.stories.tsx, packages/ui-kit/src/components/PieChart/PieChart.stories.tsx, packages/ui-kit/src/components/PieChart/PieChart.tsx, packages/ui-kit/src/components/PieChart/PieChart.types.ts, packages/ui-kit/src/components/PieChart/utils.ts, packages/ui-kit/src/hooks/useCounter/useCounter.test.tsx
=> Enable multi dimension PieChart

.changeset/violet-hotels-report.md, packages/ui-kit/src/hooks/useCounter/useCounter.ts, packages/ui-kit/src/hooks/useDataGrid/useDataGrid.ts, packages/ui-kit/src/hooks/useDataPoolColumns/useDataPoolColumns.ts, packages/ui-kit/src/hooks/useLeaderboard/useLeaderboard.ts, packages/ui-kit/src/hooks/useTimeSeries/useTimeSeries.ts
=> Fix useDataGrid broken query and `filters` not working

.changeset/fresh-feet-grow.md, packages/ui-kit/src/components/Counter/Counter.tsx, packages/ui-kit/src/components/Counter/utils.ts, packages/ui-kit/src/components/Select/Select.tsx, packages/ui-kit/src/components/shared.utils.test.ts, packages/ui-kit/src/components/shared.utils.ts
This PR fixes:
- GroupBy prettifyColumnNames not working for uppercase names
- Counter loading state flickering when filters change
- Select based components caused issues with the page layout's total height
=> Small bug fixes
