- .github/workflows/publish-pre-release.yml
- .github/workflows/publish-release.yml
- app/examples/react-16/package.json
- app/examples/react-17/package.json
- app/examples/react-18/package.json
- app/storybook/package.json
- package.json
- packages/core/components/package.json
- packages/core/graphql/package.json
- packages/core/plugins/package.json
- packages/core/release/package.json
- packages/core/release/src/index.ts
- packages/react/counter/package.json
- packages/react/leaderboard/package.json
- packages/react/time-series/package.json
- yarn.lock
With this change, the next version we will publish is 0.31.0. Merging this to main should create 0.31.0-rc.0.
@felipecadavid the actual release process will be slightly different than what we discussed yesterday, but I'll catch you up on it.
```
$ COMMIT_RELEASE=release DRY_RUN=true PRE_RELEASE=true yarn release
➤ YN0000: ┌ Determine New Versions
➤ YN0000: │ [Dry Run] [Version Change] @propeldata/ui-kit-components: 0.2.2 -> 0.31.0-rc.0 (minor, group: @propeldata/ui-kit)
➤ YN0000: │ [Dry Run] [Version Change] @propeldata/ui-kit-graphql: 0.2.8 -> 0.31.0-rc.0 (minor, group: @propeldata/ui-kit)
➤ YN0000: │ [Dry Run] [Version Change] @propeldata/ui-kit-plugins: 0.2.1 -> 0.31.0-rc.0 (minor, group: @propeldata/ui-kit)
➤ YN0000: │ [Dry Run] [Version Change] @propeldata/react-counter: 0.26.8 -> …
```
> feat: new release process

- packages/core/components/src/ErrorBoundary.tsx
- packages/core/release/src/index.ts
- packages/react/counter/src/Counter.tsx
- packages/react/counter/src/utils.ts
- packages/react/leaderboard/src/Leaderboard.tsx
- packages/react/time-series/src/TimeSeries.tsx
- packages/react/time-series/src/utils.ts
This PR fixes some bugs found while testing the components in the example apps.
- Connected mode re-fetched data on styles change
- Connected mode re-fetching on every re-render due to useEffect object dependencies
- Connected mode re-fetched data on styles change
- Connected mode re-fetching on every re-render due to useEffect object dependencies
- Switching from variant `bar` to `table` and then to `bar` again made `bar` chart disappear
- Connected mode re-fetched data on styles change
- Connected mode re-fetching on every re-render due to useEffect object dependencies
- When Connected mode receiving a `null` value, it showed an error, changed to `-` instead
- Sometimes Counter attempted to fetch data on Static mode, added !isStatic condition to fix
> Fix Counter, Leaderboard and TimeSeries bugs

- app/examples/react-18/src/components/TimeSeriesStaticTest.jsx
- packages/react/time-series/README.md
- packages/react/time-series/src/TimeSeries.tsx
- packages/react/time-series/src/defaults.ts
- packages/react/time-series/src/types.ts
- packages/react/time-series/src/utils.ts
This PR adds a `type` prop to the `styles` api in order to allow setting the y scale type to `logarithmic`
> Add `type` yAxis prop to allow logarithmic scale

- packages/core/graphql/src/index.ts
- packages/react/counter/src/Counter.tsx
- packages/react/counter/src/index.ts
- packages/react/leaderboard/src/Leaderboard.tsx
- packages/react/leaderboard/src/index.ts
- packages/react/time-series/src/TimeSeries.tsx
- packages/react/time-series/src/index.ts
This PR exports the various enums available when querying our GraphQL API. We do this, because customers want to use these constants in their apps. See https://linear.app/propel/issue/PRO-2126
Specifically,
| Enum | Relevant to… |
|:--- |:--- |
| FilterOperator | Counter, TimeSeries, Leaderboard |
| Propeller | Counter, TimeSeries, Leaderboard |
| RelativeTimeRange | Counter, TimeSeries, Leaderboard |
| Sort | Leaderboard |
| TimeSeriesGranularity | TimeSeries |
We also export some types as (like FilterInput, TimeRangeInput, etc.) as well.
```md
- We now export the enums FilterOperator, Propeller, RelativeTimeRange, and TimeSeriesGranularity.
- We also export some other Time Series-specific GraphQL types.
- We now export the enums FilterOperator, Propeller, …
```
> feat: export types

- packages/ui-kit/package.json
- packages/ui-kit/tsconfig.build.json
- packages/ui-kit/tsconfig.cjs.json
- packages/ui-kit/tsconfig.mjs.json
This PR exports the ui-kit as both CommonJS and ESM, the approach used is based on [this blogpost](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html)
This will bundle two versions of the UI-Kit, one for CommonJS and one for ESM.
```md
- Export UI-Kit as CJS and ESM.
```
> Export CommonJS modules

- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
This PR fixes [the issue with missed Chart's date adapter](https://linear.app/propel/issue/PRO-2244/bug-broken-date-adapter-in-connected-timeseries).
```md
- Fix missed Chart's date adapter.
> fix(timeseries): fix date adapter side effect

- packages/ui-kit/src/components/Counter/Counter.tsx
- packages/ui-kit/src/components/Counter/Counter.types.ts
- packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx
- packages/ui-kit/src/components/Leaderboard/Leaderboard.types.ts
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.types.ts
This PR adds the `propelApiUrl` prop to allow overriding the graphql api endpoint
```md
- Added `propelApiUrl` prop.
- Added `propelApiUrl` prop.
- Added `propelApiUrl` prop.
```
> Add `propelApiUrl` prop to set the api endpoint

- packages/ui-kit/src/components/TimeSeries/utils.test.ts
- packages/ui-kit/src/components/TimeSeries/utils.ts
This PR is a small fix for the case where no distance matches the granularity dictionary.
```md
- Fix to case where no distance matches dictionary.
```
> Small fix for labels based granularity

- .pnp.loader.mjs
- packages/ui-kit/package.json
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
- packages/ui-kit/src/components/TimeSeries/utils.test.ts
- packages/ui-kit/src/components/TimeSeries/utils.ts
- packages/ui-kit/src/themes/default.types.ts
- yarn.lock
This PR allows tooltip formatting according to granularity this way:
Granularity: DAY
Today we show: Aug 1, 2023, 12:00:00 AM
Desired value: Aug 1, 2023
Granularity: MONTH
Today we show: Aug 1, 2023, 12:00:00 AM
Desired value: August, 2023
Granularity: YEAR
Today we show: Jan 1, 2023, 12:00:00 AM
Desired value: 2023
For any granularity smaller than a day it makes sense to show the full time stamp
```md
- Format tooltip label based on granularity.
```
> Format TimeSeries tooltip according to granularity

- packages/ui-kit/src/index.ts
This PR solves [Export more types from UI Kit](https://linear.app/propel/issue/PRO-2153/export-more-types-from-ui-kit)
```md
- Export Common types
```
> fix(ui-kit): export common types

- .pnp.cjs
- packages/ui-kit/src/components/Counter/Counter.tsx
- packages/ui-kit/src/components/Counter/Counter.types.ts
- packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx
- packages/ui-kit/src/components/Leaderboard/Leaderboard.types.ts
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.types.ts
This PR solves [Remove Propeller from CounterQueryProps, LeaderboardQueryProps, and TimeSeriesQueryProps](https://linear.app/propel/issue/PRO-2400/remove-propeller-from-counterqueryprops-leaderboardqueryprops-and)
```md
- Removed `propeller` prop from the `query` props.
- Removed `propeller` prop from the `query` props.
- Removed `propeller` prop from the `query` props.
```
> chore(ui-kit): remove propeller prop

- .pnp.cjs
- .pnp.loader.mjs
- packages/ui-kit/src/components/Leaderboard/utils.ts
- yarn.lock
This PR fixes a bug that breaks the Leaderboard table when query changes
```md
- Customers will be able to change query parameters for the Leaderboard table.
```
> FIX: Table leaderboard breaking on query change

- .changeset/young-kings-tease.md
- packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
- packages/ui-kit/src/helpers/chartUtils/chartUtils.ts
This PR extends Chart.js register with `Title`, `SubTitle`, and `Legend`.
> chore(ui-kit): extend Chart.js register

- app/storybook/.storybook/manager.ts
This PR creates a setup to easily hide non-released features from storybook, we just need to add the story's title to the `devOnly` array in the `manager.ts` file, this results more useful than the `pattern` tag as we can add/remove hidden stories without having to go to each file and we will still be able to view stories in development.
```ts
const devOnly = [
'Components/PieChart',
'Hooks/useTopValues',
'Hooks/useDataGrid',
'API/DataGridQueryProps',
'API/PieChartQueryProps',
'API/TopValuesQueryProps'
]
```
I suggest we follow this line for now:
- When we create a story for a feature we add the title to the `devOnly` array
- Before releasing we clear this array in the `Version Packages` PR (hopefully we could do this automatically somehow)
> Hide non-released features from storybook

- .changeset/odd-dragons-peel.md
- packages/ui-kit/src/components/DataGrid/DataGrid.types.ts
- packages/ui-kit/src/components/FilterProvider/FilterProvider.tsx
- packages/ui-kit/src/components/PieChart/PieChart.types.ts
- packages/ui-kit/src/components/RecordsById/RecordsById.types.ts
- packages/ui-kit/src/components/TopValues/TopValues.types.ts
- packages/ui-kit/src/components/shared.types.ts
- packages/ui-kit/src/hooks/useTopValues/useTopValues.test.tsx
This PR fixes imports to use relative paths instead of `src/` as this is breaking the exported types
> Import using relative paths

- .github/workflows/publish-canary.yml
- .github/workflows/publish-release.yml
This PR fixes the `canary-release` workflow which wasn't creating canary releases
> Fix `canary-release` workflow

- .changeset/spotty-stingrays-heal.md
- packages/ui-kit/src/components/Counter/Counter.test.tsx
- packages/ui-kit/src/components/ErrorFallback/ErrorFallback.module.scss
- packages/ui-kit/src/components/ErrorFallback/ErrorFallback.tsx
- packages/ui-kit/src/components/Leaderboard/Leaderboard.test.tsx
- packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx
- packages/ui-kit/src/components/PieChart/PieChart.test.tsx
- packages/ui-kit/src/components/PieChart/PieChart.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.test.tsx
- packages/ui-kit/src/components/withContainer/withContainer.tsx
This PR fixes a bug that prevents `errorFallbackProps` from being passed correctly.
> Fix `errorFallbackProps` not being passed correctly

- .changeset/twelve-fishes-lay.md
- .github/workflows/publish-canary.yml
- packages/ui-kit/src/components/Leaderboard/Leaderboard.stories.tsx
- packages/ui-kit/src/components/Leaderboard/Leaderboard.tsx
- packages/ui-kit/src/components/PieChart/PieChart.stories.tsx
- packages/ui-kit/src/components/PieChart/PieChart.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.stories.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
When passing style changes to the `chartConfigProps` those are overriden on re-render by the default style, this is because we are not passing `chartConfigProps` to the chart options on update, here is an example of the bug:
https://github.com/propeldata/ui-kit/assets/84721399/19e789b2-7622-4aa4-9a03-19f907785175
Setting the chart options when the chart is updated as recommended in [chart.js docs](https://www.chartjs.org/docs/latest/developers/updates.html), here is an example with `scales` where `config` is the modified configuration using `chartConfigProps`
```
chart.options.scales = {
...chart.options.scales,
...scales,
...config?.options?.scales
}
```
Using `chartConfigProps` and passing it the chart instance reference to mutate the properties, we decided not to use this approach as …
> Fix chartConfigProps not passing props to the components

- .changeset/poor-dancers-explain.md
- packages/ui-kit/src/components/PieChart/PieChart.stories.tsx
- packages/ui-kit/src/helpers/chartUtils/chartUtils.ts
This PR fixes a bug with the `Total` value of the doughnut chart that is not correctly aligned when changing the position of the legends
In order to do this I changed the approach to draw the total based on the x and y coordinates of the center using the chart.js api, this is a popular approach for doing this and comes from this [tutorial](https://www.youtube.com/watch?v=c2mzQKpd_DI)
> PieChart doughnut chart Total value broken when aligning legend right

- .changeset/hip-parents-travel.md
- packages/ui-kit/src/components/PieChart/PieChart.tsx
This PR resolves [PieChart gets cut off](https://linear.app/propel/issue/PRO-2767/piechart-gets-cut-off)
| Before | After |
| --- | --- |
| ![pichart_cut](https://github.com/propeldata/ui-kit/assets/55801864/fb35618a-fd3f-43b9-bb65-c5c56b3d358f) | ![piechart_cut_after](https://github.com/propeldata/ui-kit/assets/55801864/cd724f39-48b4-47dc-b671-bb54b83efa80) |
> fix(pie-chart): adjust padding for hover state

- .changeset/fair-waves-lick.md
- packages/ui-kit/src/components/PieChart/PieChart.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.stories.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.types.ts
- packages/ui-kit/src/components/TimeSeries/utils.ts
- packages/ui-kit/src/themes/helpers/useParsedComponentProps.ts
This PR deprecates `accentColor` prop in favor of `accentColors`
> Enable setting TimeSeries accentColor via `accentColors` prop

- .changeset/modern-tomatoes-drum.md
- packages/ui-kit/src/components/TimeSeries/TimeSeries.stories.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.types.ts
This PR fixes `chartConfigProps` type for TimeSeries 
> Fix chartConfigProps incorrect type for TimeSeries

- .changeset/rotten-steaks-joke.md
- packages/ui-kit/src/components/Autocomplete/Autocomplete.tsx
- packages/ui-kit/src/components/Autocomplete/Autocomplete.types.ts
- packages/ui-kit/src/components/GroupBy/GroupBy.types.ts
- packages/ui-kit/src/components/Select/Select.tsx
- packages/ui-kit/src/components/SimpleFilter/SimpleFilter.tsx
- packages/ui-kit/src/components/SimpleFilter/SimpleFilter.types.ts
- packages/ui-kit/src/components/TimeGrainPicker/TimeGrainPicker.stories.tsx
- packages/ui-kit/src/components/TimeGrainPicker/TimeGrainPicker.tsx
- packages/ui-kit/src/components/TimeGrainPicker/TimeGrainPicker.types.ts
- packages/ui-kit/src/components/TimeRangePicker/TimeRangePicker.tsx
- packages/ui-kit/src/components/TimeRangePicker/TimeRangePicker.types.ts
This PR adds `defaultOpen` to `TimeGrainPicker`, `TimeRangePicker`, `SimpleFilter` and `GroupBy` components besides of the base `Select` and `Autocomplete`
> `defaultOpen` prop

- .changeset/tall-mirrors-speak.md
- packages/ui-kit/src/components/TimeSeries/TimeSeries.stories.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.types.ts
- packages/ui-kit/src/components/TimeSeries/utils.ts
This PR adds a `groupByColors` prop to TimeSeries that replaces `accentColors` and remove deprecated tag for `accentColor`
> TimeSeries `groupByColors` prop

- .changeset/proud-cows-hope.md
- packages/ui-kit/src/components/FilterProvider/FilterProvider.stories.tsx
- packages/ui-kit/src/components/FilterProvider/FilterProvider.test.tsx
- packages/ui-kit/src/components/FilterProvider/FilterProvider.tsx
- packages/ui-kit/src/components/FilterProvider/FilterProvider.types.ts
- packages/ui-kit/src/components/SimpleFilter/SimpleFilter.test.tsx
- packages/ui-kit/src/components/SimpleFilter/SimpleFilter.tsx
- packages/ui-kit/src/components/TimeSeries/TimeSeries.stories.tsx
- packages/ui-kit/src/components/shared.types.ts
- packages/ui-kit/src/hooks/useCounter/useCounter.ts
- packages/ui-kit/src/hooks/useDataGrid/useDataGrid.ts
- packages/ui-kit/src/hooks/useLeaderboard/useLeaderboard.ts
- packages/ui-kit/src/hooks/useTimeSeries/useTimeSeries.ts
This PR deprecates `filters` query prop and add support for `filterSql`
> Deprecate `filters` and add `filterSql`

- .changeset/five-bees-compete.md
- packages/ui-kit/src/components/ThemeProvider/ThemeProvider.tsx
This PR fixes an issue where ThemeProvider's `propel-theme` was taking precedence over component specific styles
> Fix styling precedence issue
